export type ProviderCategory =
  | "Assessment & diagnosis"
  | "Therapy clinic"
  | "ABA & behaviour support"
  | "Specialist school"
  | "School learning support"
  | "Tutoring & mentoring"
  | "Vocational & transition"
  | "Parent support"
  | "Hospital clinic"
  | "Government service"
  | "Enrichment & general learning";

export type Delivery = "At a centre" | "In school" | "At home" | "Online";

export interface Provider {
  slug: string;
  name: string;
  category: ProviderCategory;
  /** Short area label used for filtering, e.g. "Watthana" or "Online" */
  area: string;
  address?: string;
  ages?: string;
  languages?: string[];
  services: string[];
  specialisms?: string[];
  delivery?: Delivery[];
  website?: string;
  phone?: string;
  email?: string;
  facebook?: string;
  instagram?: string;
  /** Paragraphs, separated by blank lines */
  description: string;
  /** Honest caveat shown in a highlighted box */
  note?: string;
  /** Month we last checked the details */
  checked: string;
}

export const PROVIDERS: Provider[] = [
  {
    slug: "australian-therapy-services",
    name: "Australian Therapy Services",
    category: "Therapy clinic",
    area: "Online",
    ages: "Children and teenagers",
    languages: ["English", "Cantonese"],
    delivery: ["Online"],
    services: [
      "Speech and language assessment",
      "Speech therapy",
      "Occupational therapy",
      "Learning support",
      "Mental health support",
      "Group sessions",
    ],
    specialisms: ["Speech and language", "Literacy", "School liaison"],
    website: "https://australiantherapyservices.com.au",
    phone: "+66 88 805 0435",
    email: "lorelle@australiantherapyservices.com.au",
    description:
      "Australian Therapy Services delivers speech and language therapy, occupational therapy and learning support entirely online, from therapists based in Australia. Families in Bangkok book sessions the same way families in Malaysia, Vietnam and Australia do, which makes it one of the few options that does not depend on where in the city you live or how bad the traffic is on a Tuesday afternoon.\n\nThe practice is fronted by speech language pathologist Lorelle Evans. Sessions are set up so that a parent or a class teacher can sit in and watch, which matters if you want the strategies carried across into the classroom rather than staying locked inside the therapy hour. Listed hours are Monday to Friday, 8:00 to 22:00, which covers most Bangkok school timetables.\n\nOnline therapy is not right for every child. Very young children, children who need hands-on occupational therapy, and children who struggle to stay at a screen usually do better in a room with a therapist. It suits older children, follow-up blocks and families outside easy reach of the Sukhumvit clinics.",
    checked: "September 2026",
  },
  {
    slug: "brainfit-thailand",
    name: "BrainFit Thailand",
    category: "Enrichment & general learning",
    area: "Khlong Toei",
    address:
      "Room 5, 2nd Floor, Ploenchit Center, Sukhumvit Soi 2, Khlong Toei, Bangkok 10110 (BTS Ploenchit Exit 4)",
    ages: "3 to 18",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "CognitiveMAP assessment",
      "BrainFit Junior, ages 3 to 6",
      "BrainFit Scholar, ages 7 to 18",
      "Fast ForWord and ClearFluency language programmes",
      "Attention and handwriting programmes",
      "Holiday programmes",
    ],
    specialisms: ["Attention", "Working memory", "Reading fluency"],
    website: "https://www.brainfit.co.th/en/",
    description:
      "BrainFit runs structured cognitive training programmes for children aged 3 to 18, built around attention, memory, listening and motor coordination rather than subject tutoring. Children start with a CognitiveMAP assessment and are then placed into a programme track: play-based BrainFit Junior for the early years, or BrainFit Scholar for school-age children working on the skills that sit underneath reading and maths.\n\nThe centre licenses Fast ForWord and ClearFluency, both established computer-based language and reading programmes, and runs shorter holiday intensives. It is a convenient location, a two-minute walk from BTS Ploenchit.",
    note: "This is a commercial cognitive-training centre, not a clinical or diagnostic service. If you are trying to find out whether your child has dyslexia, ADHD or a language disorder, start with an assessment provider or a paediatrician instead, then decide whether a programme like this fits alongside it.",
    checked: "September 2026",
  },
  {
    slug: "building-bridges-bangkok",
    name: "Building Bridges Behavior Consulting",
    category: "ABA & behaviour support",
    area: "Watthana",
    address:
      "S.C. Mansion, 90 Charoen Chai Alley, Khlong Tan Nuea, Watthana, Bangkok 10110",
    ages: "2 through high school",
    languages: ["English", "Thai"],
    delivery: ["At a centre", "In school", "At home", "Online"],
    services: [
      "One-to-one ABA therapy",
      "School-based support and shadowing",
      "In-home programmes",
      "Telehealth sessions",
      "Group therapy",
      "Parent training",
      "School staff training and professional development",
    ],
    specialisms: [
      "Autism",
      "Communication",
      "Social skills",
      "Emotional regulation",
      "Behaviour",
    ],
    website: "https://www.buildingbridgesbangkok.com",
    phone: "+66 90 996 9062",
    email: "info@buildingbridgesbangkok.com",
    description:
      "Building Bridges applies behaviour analysis to communication, social skills, learning and emotional regulation, for children from around age 2 up through high school. The practice is led by Board Certified Behavior Analysts, which is worth noting: BCBA certification is an international credential with its own supervision and ethics requirements, and not every provider in Bangkok offering ABA has one on staff.\n\nWhat sets them apart practically is delivery flexibility. The same programme can run at their Khlong Tan Nuea clinic, inside your child's school, at your home, or over telehealth, which matters when a child needs support generalised across settings rather than performed once a week in a clinic room.\n\nThey also train school staff and run professional development, so if your child's school is willing but under-skilled, this is one of the routes to getting the classroom team up to speed.",
    checked: "September 2026",
  },
  {
    slug: "care-child-professional-school",
    name: "CARE Child Professional School (CARE Thailand)",
    category: "ABA & behaviour support",
    area: "Bang Kho Laem",
    address:
      "168 Thai Eye Center, Charoen Rat Road, Bang Kho Laem, Bangkok 10150",
    ages: "0 to 26",
    languages: ["English", "Thai"],
    delivery: ["At a centre", "In school"],
    services: [
      "Early intensive intervention, ages 0 to 3",
      "School readiness, ages 3 to 6",
      "Individual pathways, ages 6 to 18",
      "Young adult transition, ages 18 to 26",
      "School shadow support",
      "Supervision packages for other providers",
      "Training workshops",
    ],
    specialisms: ["Autism", "Developmental delay", "Life skills", "Independence"],
    website: "https://www.carethailand.co.th",
    phone: "+66 2 689 1818",
    email: "contact.info@carethaiautism.com",
    description:
      "CARE runs ABA-based programmes organised into four clear age bands, from intensive early intervention for under-threes through to a transition programme for young adults up to 26. That last band is unusual in Bangkok. Most providers stop at school-leaving age, and families of older teenagers often find the options thin.\n\nThe stated emphasis is on independence, life skills and taking part in the community rather than clinic-bound drills. Supervisors sit in on sessions regularly, and the team runs training in both Thai and English, which makes them a reasonable option for mixed-language households and for Thai school staff who need coaching.\n\nThey are on Charoen Rat Road in Bang Kho Laem, which is south-west of the usual Sukhumvit cluster. Factor the trip into your thinking if you are committing to several sessions a week.",
    checked: "September 2026",
  },
  {
    slug: "clue-ei-centre",
    name: "CLUE EI Centre",
    category: "Therapy clinic",
    area: "Bangkok",
    ages: "Children, teenagers and adults",
    languages: ["English", "Thai"],
    delivery: ["At a centre", "In school", "At home"],
    services: [
      "Speech and language evaluation",
      "Speech and language intervention",
      "On-site sessions at childcare centres, preschools and schools",
      "Home visits",
    ],
    specialisms: [
      "Language disorders",
      "Articulation",
      "Auditory processing disorder",
      "Verbal apraxia",
      "Voice and resonance",
      "Stuttering",
    ],
    website: "https://www.cluecentre.com",
    phone: "+66 64 635 4954",
    email: "info@cluecentre.com",
    description:
      "CLUE is a speech-language pathology practice covering the full range of communication difficulties: expressive and receptive language, articulation, auditory processing, verbal apraxia, voice, resonance and fluency. The team pairs speech pathologists with early educators trained to work with children who have additional needs, including intellectual disability.\n\nThe detail parents tend to care most about is that they will travel. Sessions can happen at a childcare centre, a preschool, a school or at home rather than only at the clinic, which removes a lot of the logistical friction that causes families to quietly drop out of therapy after a few months.\n\nListed hours are Monday to Saturday, 8:00 to 18:00, with Sunday by appointment. Saturday availability is genuinely useful if both parents work.",
    checked: "September 2026",
  },
  {
    slug: "hope-center-for-learning",
    name: "HOPE Center for Learning",
    category: "Tutoring & mentoring",
    area: "Phra Khanong (Bang Chak)",
    address: "Bang Chak, a short walk from BTS Bang Chak Exit 1",
    ages: "5 and above",
    languages: ["English"],
    delivery: ["At a centre"],
    services: [
      "English-medium childcare",
      "Tutorials",
      "Primary-level teaching",
      "English lending library",
      "Indoor play space",
    ],
    specialisms: ["English literacy", "Small-group teaching"],
    phone: "+66 61 447 3002",
    email: "hopecenterbkk@gmail.com",
    facebook: "https://www.facebook.com/HOPEcenterbkk/",
    description:
      "Holistic Primary Education, shortened to HoPE, is a small home-based learning centre in Bang Chak offering English-medium childcare, tutoring and primary teaching for children aged 5 and up. It was started by a mother who wanted good English-language schooling for her own child at a price ordinary families could meet, and it has stayed small: a mini library, a learning area and an indoor play space, a few steps from the BTS.\n\nFor families squeezed out of international school fees who mainly need English support and a warm, low-pressure setting, it is worth a conversation.",
    note: "This is a general tutoring and childcare centre rather than a specialist learning support service. It does not advertise SEN-trained staff, therapists or assessment. If your child has an identified need, ask directly what experience they have with it before enrolling.",
    checked: "September 2026",
  },
  {
    slug: "isb-intensive-learning-center",
    name: "ISB Intensive Learning Center",
    category: "School learning support",
    area: "Nonthaburi (Pak Kret)",
    address: "International School Bangkok, Nichada Thani, Pak Kret, Nonthaburi",
    ages: "School age, enrolled students",
    languages: ["English"],
    delivery: ["In school"],
    services: [
      "Learning Support Program for mild to intensive needs",
      "Intensive Learning Center placement",
      "Small group instruction",
      "Co-teaching and in-class support",
      "Individual education plans",
      "Speech, occupational therapy and psychology on site",
    ],
    specialisms: [
      "Intellectual disability",
      "Developmental disability",
      "Life skills",
      "Highly able learners",
    ],
    website: "https://www.isb.ac.th",
    email: "admissions@isb.ac.th",
    description:
      "ISB's learning support runs on a continuum. Most students with mild or moderate needs are supported inside mainstream classes through differentiated instruction, accommodations, co-teaching and small group sessions. Students with intellectual or developmental disabilities who need a highly individualised programme are placed in grade-level homerooms and receive specialist instruction in the Intensive Learning Center, taught by a trained special educator with assistants.\n\nThe in-house team is the draw: certified special educators alongside speech-language pathologists, occupational therapists and school psychologists, all employed by the school rather than contracted in. Very few schools in Bangkok carry that depth on staff.\n\nPlaces are limited and admission is a separate conversation from general school admission, so raise learning needs early rather than after an offer.",
    note: "Open only to students enrolled at ISB. If you are considering the school specifically for this programme, contact admissions about the learning support intake before you apply.",
    checked: "September 2026",
  },
  {
    slug: "julia-gabriel-centre-bangkok",
    name: "Julia Gabriel Centre Bangkok",
    category: "Enrichment & general learning",
    area: "Huai Khwang (Mengjai)",
    ages: "6 months to primary",
    languages: ["English", "Mandarin"],
    delivery: ["At a centre"],
    services: [
      "PlayNest and PlayClub early years classes",
      "Speech and Drama, nursery and kindergarten",
      "I Love Reading",
      "Let's Read and Write",
      "Mandarin Language Learners",
    ],
    specialisms: ["Confidence and expression", "Early literacy", "Spoken English"],
    website: "https://juliagabriel.co.th",
    phone: "+66 81 624 5141",
    email: "enquiries.bkk@juliagabriel.co.th",
    description:
      "The Singapore-founded Julia Gabriel Centre teaches through EduDrama, an approach that puts language learning inside performance and play. The Bangkok centre runs early years classes from six months, speech and drama through nursery and kindergarten, and reading and writing programmes for young primary children, plus Mandarin.\n\nFor a child who is quiet, reluctant to speak up, or behind their peers in spoken confidence, drama-based classes can do real work. Plenty of families use it as a gentler alternative to academic tutoring.",
    note: "Speech and drama is not speech therapy. If you are worried about a speech or language disorder, see a speech-language pathologist. This is enrichment, and the two are often confused because of the word 'speech'.",
    checked: "September 2026",
  },
  {
    slug: "kensington-learning-space",
    name: "Kensington Learning Space",
    category: "Enrichment & general learning",
    area: "Taling Chan",
    address: "88/9 Bang Phrom 16, Ratchaphruek Road, Taling Chan, Bangkok 10170",
    ages: "4 months to 11, plus adult classes",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Early years developmental classes",
      "After-school and weekend classes",
      "STEAM, maths and language",
      "Dance, art and sports",
      "Forest School and aquatics",
      "Holiday camps and workshops",
    ],
    website: "https://klearningspace.com",
    phone: "+66 99 245 7777",
    email: "info.kls@kensington.ac.th",
    description:
      "Kensington Learning Space is a large, architecturally striking learning centre on the Thonburi side, running classes for children from four months to eleven years across dance, art, sport, STEAM, maths, languages, astronomy, aquatics and forest school, plus holiday camps. The building itself has won design awards, and the indoor and outdoor spaces are a genuine draw for families west of the river who are tired of driving across town.",
    note: "We could not find any published specialist learning support, SEN provision or therapy service here. It appears on some learning support lists, but on the evidence available it is a general enrichment centre. We have listed it so you are not left wondering, and labelled it honestly.",
    checked: "September 2026",
  },
  {
    slug: "leap-bangkok",
    name: "LEAP Bangkok",
    category: "Parent support",
    area: "Bangkok",
    ages: "Parents and families",
    languages: ["English"],
    delivery: ["At a centre", "Online"],
    services: [
      "Parent-to-parent mentoring",
      "Referrals to assessors and therapists",
      "Seminars and workshops",
      "Informal coffee meet-ups",
    ],
    specialisms: [
      "Learning difficulties",
      "Developmental delay",
      "Sensory integration",
      "Attention",
      "Autism",
    ],
    email: "leapbangkok@gmail.com",
    description:
      "LEAP, the Learning and Educational Advocacy Program, is a parent-run support and advocacy group for families of children with additional learning and developmental needs. It connects newer parents with those further down the road, points families toward assessors and therapists, and runs seminars, workshops and informal coffee mornings on learning difficulties, developmental delay, sensory integration, attention and autism.\n\nThere is no fee and no clinical service here. What it gives you is the thing that is hardest to buy: other parents who have already worked out which assessment is worth paying for, which school actually delivers what it promises, and how to get a school to act.",
    note: "Do not confuse this with the US organisation of the same name and acronym, which operates in Palm Beach County, Florida. They are unrelated. Search results mix them up constantly.",
    checked: "September 2026",
  },
  {
    slug: "little-sprouts-childrens-centre",
    name: "Little Sprouts Children's Centre",
    category: "Therapy clinic",
    area: "Watthana (Thong Lo)",
    address: "109/1 Soi Thong Lo 5, Sukhumvit 55, Watthana, Bangkok 10110",
    ages: "12 months to 11, some specialists see teenagers",
    languages: ["English", "Thai", "Mandarin"],
    delivery: ["At a centre", "In school"],
    services: [
      "Developmental and psychological assessment",
      "Speech and language therapy",
      "Occupational therapy",
      "Early intervention programme",
      "Social skills groups",
      "Counselling and play therapy",
      "Music therapy",
      "Language and literacy programme",
      "Inclusive pre-nursery",
      "School outreach",
    ],
    specialisms: [
      "Autism",
      "ADHD",
      "Developmental delay",
      "Dyslexia",
      "Sensory processing",
      "Anxiety and low mood",
    ],
    website: "https://littlesproutscentre.com",
    phone: "+66 2 712 5204",
    email: "info@littlesproutscentre.com",
    description:
      "Little Sprouts is the closest thing Bangkok has to a one-stop multidisciplinary children's clinic, and it is the name that comes up most often when expat parents ask other expat parents where to start. Assessment, speech therapy, occupational therapy, psychology, early intervention, social skills groups, music therapy and literacy support all sit under one roof on Thong Lo 5.\n\nThat matters more than it sounds. When a child needs a speech therapist and an occupational therapist and an educational psychologist, having them in the same building means they talk to each other, and you are not stitching together three separate opinions yourself.\n\nServices run in English, Thai and Mandarin, and the team includes specialists with training in areas that are hard to find locally, including feeding, motor speech disorders, selective mutism and childhood apraxia. They also do school outreach, so a therapist can observe your child in class.\n\nThey are popular, which means waiting lists. Ask about timelines on the first call rather than assuming you can start next week.",
    checked: "September 2026",
  },
  {
    slug: "merak-clinic",
    name: "Merak Clinic",
    category: "Therapy clinic",
    area: "Nonthaburi",
    address: "146/5 Tiwanon Road, Tha Sai, Mueang, Nonthaburi 11000",
    ages: "Children through adults",
    languages: ["English", "Thai"],
    delivery: ["At a centre", "In school"],
    services: [
      "Developmental and behavioural assessment",
      "Early intervention",
      "Family and couples counselling",
      "Play therapy",
      "Cognitive behavioural therapy",
      "Music and art therapy",
      "Applied behaviour analysis",
      "Parenting skills training",
      "School consultation",
    ],
    specialisms: [
      "Developmental concerns",
      "Behaviour",
      "Anxiety and depression",
      "Family relationships",
    ],
    website: "https://www.merakclinic.com",
    phone: "+66 84 733 0444",
    email: "merakclinic@hotmail.com",
    description:
      "Merak is a multidisciplinary child and adolescent mental health clinic covering developmental, behavioural, emotional and learning concerns, with a team that spans psychology, therapy and behaviour analysis. The service range is wide: early intervention for young children, play therapy and CBT, music and art therapy, ABA, parenting programmes, family counselling and school consultation, and they see adults as well as children.\n\nBecause they cover both the developmental and the mental health side, they are a sensible option for older children and teenagers whose learning difficulty has become tangled up with anxiety, school refusal or family stress, which is more common than most people expect.",
    note: "Merak is in Nonthaburi, north of the city, not central Bangkok. For families in Sukhumvit or Sathorn this is a long trip. Check the journey before committing to a weekly slot.",
    checked: "September 2026",
  },
  {
    slug: "new-day-learning",
    name: "New Day Learning & Therapy Clinic (NDL)",
    category: "Specialist school",
    area: "Bangkok",
    ages: "Early years through teenagers",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Assessment and evaluation",
      "Occupational therapy",
      "Speech and language therapy",
      "Literacy support",
      "Braille instruction",
      "Early intervention",
      "Life skills and education for teenagers",
      "English as an additional language",
      "Thai language",
      "Camps and clubs",
      "Professional development training",
    ],
    specialisms: [
      "Special educational needs",
      "Literacy",
      "Visual impairment",
      "Multisensory teaching",
    ],
    website: "https://newdaylearningco.com",
    email: "newdaylearning@ndlbkk.com",
    description:
      "New Day Learning sits in the space between a school and a clinic. It teaches an adapted UK curriculum in small classes using multisensory methods, and delivers occupational therapy, speech and language therapy, literacy support and early intervention alongside the teaching. For teenagers there is a life skills and education track.\n\nTwo details are worth knowing. It is licensed through Thailand's Ministry of Public Health under licence number 10109002562, and it is an approved Pearson BTEC centre, so students can work toward recognised vocational qualifications rather than leaving with nothing formal.\n\nIt is also one of very few places in Bangkok offering Braille instruction, which makes it the obvious first call for families of children with visual impairment.",
    checked: "September 2026",
  },
  {
    slug: "no-limits",
    name: "No Limits",
    category: "ABA & behaviour support",
    area: "Watthana",
    address:
      "Muban Kasem Samran 2 Soi 5, Phra Khanong Nuea, Watthana, Bangkok 10110",
    ages: "Early years through school age",
    languages: ["English", "Thai"],
    delivery: ["At a centre", "In school", "At home"],
    services: [
      "Centre-based social skills and sensory programmes",
      "In-home support and respite",
      "School partnerships and in-class support",
      "Family training workshops",
      "Early childhood intervention",
    ],
    specialisms: ["Autism", "ADHD", "Behaviour", "Social development"],
    website: "https://nolimitscs.com",
    phone: "+66 63 331 9266",
    email: "info@nolimitscs.com",
    description:
      "No Limits provides SEND support for children with autism, ADHD and other developmental differences, working across its own centre, families' homes and partner schools. The offer covers social skills and sensory programmes, early intervention, behaviour and social development support, and family training.\n\nThe in-home and respite element is the part parents should notice. Respite is badly under-supplied in Bangkok, and a service that will come to your home rather than requiring you to get a dysregulated child across the city is worth a lot. They cover Sukhumvit, Thong Lo, Ekkamai, Phrom Phong, Asok, Silom, Sathorn and the surrounding areas, in English and Thai.",
    checked: "September 2026",
  },
  {
    slug: "north-light-center",
    name: "North Light Center for Special Needs Children",
    category: "Therapy clinic",
    area: "Phaya Thai",
    address: "116/6 Rama VI Soi 39, Phaya Thai, Bangkok 10400",
    ages: "Newborn through school age",
    languages: ["Thai"],
    delivery: ["At a centre", "Online"],
    services: [
      "Hearing assessment and evaluation",
      "Hearing technology consultation",
      "Listening and spoken language development",
      "Individual hearing training and speech rehabilitation",
      "Intensive language development programmes",
      "Parent education and coaching",
      "Occupational therapy developmental stimulation",
    ],
    specialisms: [
      "Deaf and hard of hearing",
      "Listening and spoken language",
      "Cochlear implants and hearing aids",
    ],
    website: "https://northlightcenter.com",
    phone: "+66 2 271 4455",
    description:
      "North Light is a specialist centre for deaf and hard of hearing children, from newborns through school age. It covers hearing assessment, guidance on hearing technology, listening and spoken language development, individual hearing training and speech rehabilitation, intensive language programmes and occupational therapy for developmental stimulation, with a strong parent coaching component.\n\nThis is a narrow specialism done properly, and there is very little else like it in Bangkok. If a newborn hearing screen has flagged something, or a hearing aid or cochlear implant has been fitted and you need the listening and language work that has to follow, this is the place to ask about.\n\nOpening hours are Monday to Friday 9:00 to 17:00 and Saturday 8:00 to 17:00.",
    note: "The centre's website and services are in Thai. Expat families without Thai may want to bring a Thai-speaking friend or interpreter to the first appointment.",
    checked: "September 2026",
  },
  {
    slug: "ris-learning-support",
    name: "RIS Ruamrudee Learning Support",
    category: "School learning support",
    area: "Min Buri",
    address: "Ruamrudee International School, Min Buri, Bangkok",
    ages: "Pre-K to Grade 12, enrolled students",
    languages: ["English"],
    delivery: ["In school"],
    services: [
      "Psychological and educational evaluation",
      "In-class and pull-out academic support",
      "Individual learning goals",
      "Team referral process with counsellor and school psychologist",
    ],
    specialisms: ["Reading", "Writing", "Mathematics", "Learning difficulties"],
    website: "https://www.rism.ac.th",
    phone: "+66 2 791 8900",
    email: "info@rism.ac.th",
    description:
      "RIS runs a Learning Support programme spanning Pre-K to Grade 12 for students with identified difficulties in reading, writing or maths. Entry is not informal. A referral triggers a full psychological and educational evaluation of a student's academic, cognitive and social-emotional profile, the results are discussed with parents and teachers, and only then is a student enrolled in the programme. Exiting requires a similar assessment.\n\nThat structure is a genuine strength. It means support is based on data rather than a teacher's hunch, and that a child is not parked in a support programme indefinitely once they no longer need it.",
    note: "Available to enrolled RIS students only. Raise learning needs during the admissions conversation, not after.",
    checked: "September 2026",
  },
  {
    slug: "sen-tutors",
    name: "SEN Tutors",
    category: "Tutoring & mentoring",
    area: "Bangkok",
    ages: "Children and young people",
    languages: ["English"],
    delivery: ["At home", "Online"],
    services: [
      "One-to-one SEN tuition",
      "Mentoring",
      "Executive function coaching",
    ],
    specialisms: [
      "Autism",
      "ADHD traits",
      "Mild learning difficulties",
      "Social, emotional and mental health needs",
      "Anxiety",
    ],
    description:
      "SEN Tutors offers bespoke one-to-one tuition and mentoring from tutors experienced in neurodivergent education, plus executive function coaching, the practical work of planning, starting tasks, managing time and keeping track of deadlines that so often derails otherwise capable teenagers. The stated range covers autism, ADHD traits, mild learning difficulties, social, emotional and mental health needs, trauma and anxiety. Sessions are available seven days a week.",
    note: "We could not verify a phone number, email address or current website for this service from an independent source. Ask for tutor qualifications and references before booking, as you would with any private tutor.",
    checked: "September 2026",
  },
  {
    slug: "spark-centre",
    name: "Spark Centre",
    category: "Therapy clinic",
    area: "Bangkok and Nakhon Nayok",
    address:
      "Bangkok centre, plus Farm De Lek, 43 Moo 3, Tambon Khlong Yai, Amphoe Ongkharak, Nakhon Nayok 26120",
    ages: "Children and young people",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Outdoor and nature-based programmes",
      "Play and art-based sessions",
      "Animal-assisted activities",
      "Individualised programming",
      "Farm-based residential and day activities",
    ],
    specialisms: ["Autism", "Neurodiversity", "Confidence and social skills"],
    phone: "+66 96 774 3610",
    email: "info@sparkcentre.net",
    facebook: "https://www.facebook.com/sparkcentrethailand",
    instagram: "https://www.instagram.com/sparkcentrethailand",
    description:
      "Spark Centre is a social enterprise founded by Premrudee Pantrat and Narawadee Bualert, both of whom came to it through their own families. The premise is that the outdoors, animals, art and play do things a clinic room cannot, and the programming is built around that rather than around a therapy timetable.\n\nAlongside the Bangkok centre they run Farm De Lek in Nakhon Nayok, roughly two hours out of the city, which opens up longer farm-based sessions and a genuine change of environment. For a child who has stalled or shut down in conventional therapy settings, this is a legitimately different approach worth considering.",
    note: "Their sparkcentre.net web address currently redirects to an unrelated third-party site, which usually means a lapsed domain rather than anything to do with the organisation. Use their Facebook or Instagram pages to make contact instead, and do not enter any details on the redirected page.",
    checked: "September 2026",
  },
  {
    slug: "st-andrews-sukhumvit-107",
    name: "St Andrews International School Sukhumvit 107",
    category: "Vocational & transition",
    area: "Bang Na",
    address: "Sukhumvit 107, Bang Na, Bangkok",
    ages: "Secondary and post-16",
    languages: ["English", "Thai"],
    delivery: ["In school"],
    services: [
      "On-campus Steps vocational training centre",
      "Student-run cafe",
      "Alternative education pathway alongside mainstream school",
      "Life skills and transition support",
    ],
    specialisms: ["Autism", "Neurodiversity", "Employability", "Transition"],
    website: "https://www.standrews-schools.com",
    email: "sukhumvit@standrews-schools.com",
    description:
      "St Andrews Sukhumvit 107 brought the Steps vocational model onto a mainstream school campus, with a training centre and cafe on site where neurodivergent students follow an alternative pathway without leaving the school community. It is the first time the full Steps model has been built into a wider academic environment in Thailand.\n\nThe question it answers is the one that keeps parents of older children awake: you found therapy and learning support for a small child, and then what? This is an attempt at a real answer, a route through secondary school that ends in life skills and employability rather than a cliff edge at sixteen.\n\nIt also does something quieter for the mainstream students, who grow up in a school where this is simply normal.",
    checked: "September 2026",
  },
  {
    slug: "st-andrews-learning-support-services-centre",
    name: "St Andrews Learning Support Services Centre (STA-LSSC)",
    category: "School learning support",
    area: "Sathorn and Watthana",
    address: "St Andrews International School Bangkok campuses",
    ages: "Primary and high school, enrolled students",
    languages: ["English"],
    delivery: ["In school"],
    services: [
      "STARS primary programme",
      "Embracing Differences high school programme",
      "Classes capped at 8 students",
      "One-to-one learning support assistants",
      "Speech and language therapy",
      "Occupational therapy",
      "Art and play therapy",
      "Physiotherapy",
      "Sensory rooms and therapy spaces",
    ],
    specialisms: [
      "Complex needs",
      "Functional and social skills",
      "Community access",
      "Vocational preparation",
    ],
    website:
      "https://www.nordangliaeducation.com/sta-bangkok/academic-excellence/special-educational-needs",
    phone: "+66 2 056 9555",
    email: "admissions@standrews.ac.th",
    description:
      "St Andrews runs two linked specialist programmes: STARS in the primary school and Embracing Differences in the high school, so a child does not fall off a support cliff at age eleven. Classes are capped at eight students, with one-to-one learning support assistants and SEND specialist teachers.\n\nThe transdisciplinary team is the standout. Speech and language therapists, occupational therapists, art therapists, play therapists and physiotherapists work alongside the teaching staff rather than being bought in by the hour, and the campuses have purpose-built sensory rooms, movement areas, therapy spaces and accessible classrooms.\n\nTeaching is pitched at each child's edge of learning, with deliberate work on functional and social skills, community access and, later, vocational opportunities, so that skills transfer into real settings rather than staying in the classroom.",
    note: "For students enrolled at St Andrews. Contact the admissions team about the specialist programmes specifically, as intake is separate from mainstream admission.",
    checked: "September 2026",
  },
  {
    slug: "steps",
    name: "Steps (Steps with Theera)",
    category: "Vocational & transition",
    area: "Watthana (Ekkamai)",
    address:
      "29/8 Charoenmit, Ekkamai Soi 10, Sukhumvit 63, Watthana, Bangkok 10110",
    ages: "Teenagers and young adults",
    languages: ["English", "Thai", "Japanese"],
    delivery: ["At a centre", "In school"],
    services: [
      "Life Skills programme",
      "Preparation for the Future programme",
      "Transition to Employment",
      "Summer programme",
      "Steps cafes as training workplaces",
      "Business Services Centre",
      "Inclusion consulting for employers and schools",
      "ASDAN and BTEC pathways",
    ],
    specialisms: [
      "Neurodiversity",
      "Employability",
      "Independence",
      "Vocational training",
    ],
    website: "https://www.stepscommunity.com",
    phone: "+66 81 819 6967",
    email: "info@stepscommunity.com",
    description:
      "Steps is a Bangkok social enterprise built around a simple, stubborn problem: neurodivergent young people leave education and then find nothing waiting for them. Its programmes run from life skills through preparation for the future to actual transition into employment, backed by ASDAN and BTEC pathways so students finish with recognised qualifications.\n\nThe training happens in real workplaces the organisation itself runs, including the Steps cafes and a business services centre, which means students practise in a genuine commercial setting with genuine customers rather than a simulated one. Steps also consults with employers and schools on inclusion, which is how the model reached St Andrews Sukhumvit 107.\n\nIt is a certified B Corporation and a member of the Valuable 500, and it works in English, Thai and Japanese. If you have a teenager and you are starting to think about what comes after school, put this on the list early rather than in the final year.",
    checked: "September 2026",
  },
  {
    slug: "sunshine-child-and-family-development-center",
    name: "SunShine Child and Family Development Center",
    category: "Therapy clinic",
    area: "Bangkok",
    ages: "Children and families",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Play therapy",
      "Early intervention",
      "Counselling",
      "Positive parenting training",
      "Individualised programmes",
    ],
    specialisms: [
      "Learning challenges",
      "Social and emotional development",
      "Behaviour",
      "Parenting",
    ],
    phone: "+66 81 661 5551",
    email: "sunshine.childandfamily@gmail.com",
    description:
      "SunShine works on children's psychological wellbeing and on the family around the child, combining play therapy, early intervention and counselling with structured positive parenting training that teaches caregivers about child development, behaviour and basic positive discipline.\n\nThe parenting side is the part worth flagging. A meaningful share of what looks like a child's learning or behaviour problem responds to changes in how the adults around them respond, and relatively few Bangkok providers put real weight on coaching parents rather than only treating the child.",
    checked: "September 2026",
  },
  {
    slug: "dove-programme-elc",
    name: "The Dove Programme at ELC International Schools",
    category: "Specialist school",
    area: "Bangkok",
    address: "ELC The City School, Bangkok",
    ages: "3 to 11",
    languages: ["English"],
    delivery: ["In school"],
    services: [
      "Small classes of 4 to 6 children",
      "Communication support including AAC, sign language and visual supports",
      "Emotional regulation support",
      "Sensory processing support",
      "Daily living skills",
      "Ontario Curriculum adapted for neurodiverse learners",
      "Summer programme",
    ],
    specialisms: [
      "Complex communication needs",
      "Autism",
      "Sensory processing",
      "Functional life skills",
    ],
    website: "https://www.elc.ac.th/schools/city-school/the-dove-programme/",
    phone: "+66 2 381 2919",
    email: "admissions@elc.ac.th",
    description:
      "Dove sits within ELC's Student Services and Wellbeing provision at The City School and takes children aged 3 to 11 with significant support needs, in classes of just four to six. A multidisciplinary team of educators, therapists and disability specialists works transdisciplinarily, meaning the therapy goals are embedded in the school day rather than bolted on.\n\nThe communication provision is notably serious: augmentative and alternative communication, sign language and visual supports are all used, alongside work on emotional regulation, sensory processing and daily living skills. Academically it follows the Ontario Curriculum, adapted for neurodiverse learners, with functional life skills and social development given equal billing.\n\nA class of four to six with a therapist-embedded team is about as intensive as mainstream-adjacent schooling gets in Bangkok. There is also a summer programme, which is a low-commitment way to see whether the setting suits your child.",
    checked: "September 2026",
  },
  {
    slug: "the-dyslexia-hub",
    name: "The Dyslexia Hub",
    category: "Assessment & diagnosis",
    area: "Watthana (Asok)",
    ages: "8 to 16",
    languages: ["English"],
    delivery: ["At a centre"],
    services: [
      "Full diagnostic dyslexia assessment",
      "Written report with learning profile",
      "Classroom strategy recommendations",
      "Guidance on exam access arrangements",
    ],
    specialisms: ["Dyslexia", "Literacy difficulties", "Exam access arrangements"],
    email: "admin@thedyslexiahub.com",
    description:
      "The Dyslexia Hub does one thing: full diagnostic dyslexia assessments for children aged 8 to 16, in person in the Asok area. The assessor is trained in line with British Dyslexia Association guidance and professional standards, which matters if the report needs to be accepted by a British-curriculum school or an exam board.\n\nThe output is a detailed written report mapping strengths as well as difficulties, with practical recommendations aimed at things a class teacher can actually start doing on Monday, plus guidance on next steps and, where appropriate, exam access arrangements such as extra time.\n\nThat last point is the one parents underestimate. An IGCSE or A Level access arrangement generally needs evidence from a properly qualified assessor, obtained well before the exam series, not a note from a tutor.",
    checked: "September 2026",
  },
  {
    slug: "the-rainbow-room",
    name: "The Rainbow Room",
    category: "Parent support",
    area: "Bangkok",
    ages: "Families, siblings and individuals of all ages",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Parent-to-parent support group meetings",
      "Sibling support and social activities",
      "Monthly talks",
      "Parent workshops for self-development and self-care",
      "Inclusive play groups",
      "Family activities",
      "Lending library",
      "Self-advocacy programmes",
    ],
    specialisms: [
      "Down syndrome",
      "Autism",
      "Cerebral palsy",
      "ADHD",
      "Genetic conditions",
    ],
    website: "https://therainbowroom.org",
    phone: "+66 2 023 2396",
    email: "hello@therainbowroom.org",
    description:
      "The Rainbow Room is a non-profit neurodiversity awareness centre run by and for parents, families and friends of people with developmental and behavioural differences, including Down syndrome, autism, cerebral palsy, ADHD and genetic conditions. It works on a parent-to-parent model: information, experience and encouragement passed between families rather than delivered from above.\n\nThe programme is broader than a support group. There are regular parent meetings, monthly talks, workshops aimed squarely at parents' own wellbeing rather than their child's, inclusive play groups that mix children of different ages and abilities with their siblings, family activities, a lending library of books and research, and self-advocacy programmes for the individuals themselves.\n\nThe sibling support deserves a special mention. Brothers and sisters carry a lot and are rarely given anywhere to put it down.",
    note: "The security certificate on their website had expired when we checked, so your browser may warn you. Phone or email works reliably.",
    checked: "September 2026",
  },

  // ---------------------------------------------------------------
  // Providers not listed on the directory this page was benchmarked against
  // ---------------------------------------------------------------

  {
    slug: "the-village-international-education-centre",
    name: "The Village International Education Centre",
    category: "Specialist school",
    area: "Khlong Toei (Phra Khanong)",
    address:
      "14 Soi Sukhumvit 42, Sukhumvit Road, Phra Khanong, Khlong Toei, Bangkok 10110",
    ages: "2 to 19 and above",
    languages: ["English", "Thai", "Japanese"],
    delivery: ["At a centre", "In school"],
    services: [
      "Early learning and primary",
      "Middle and high school",
      "ASDAN Life Skills programme",
      "COPE Award and GED pathways",
      "Transitional programmes back to mainstream",
      "Speech and language therapy",
      "Occupational therapy",
      "Behaviour support",
      "Educational psychology and dyslexia assessment",
    ],
    specialisms: [
      "Special educational needs",
      "Individual education plans",
      "Life skills",
      "Employment access",
    ],
    website: "https://www.village-education.com",
    phone: "+66 2 391 4453",
    email: "harshi@village-education.com",
    description:
      "The Village is a full specialist school on Sukhumvit 42 taking students from age 2 through to young adults of 19 and above, built around individual education programmes for children who have found mainstream schooling difficult. It teaches the English National Curriculum alongside ASDAN Life Skills, the COPE Award and a US GED pathway, and delivers speech and language therapy, occupational therapy, behaviour support, educational psychology and dyslexia assessment in house.\n\nOne of its more useful features is the transitional programme, designed for children who need focused work on specific difficulties before returning to a mainstream school, rather than treating a move to specialist provision as permanent.\n\nPrincipal Harshi Sehmar was appointed MBE by King Charles III in 2024 for nearly three decades in special needs education. The school works in English, Thai and Japanese.",
    checked: "September 2026",
  },
  {
    slug: "speech-station",
    name: "Speech Station",
    category: "Therapy clinic",
    area: "Bang Khae",
    address:
      "170/30 The Trio Avenue, Phutthamonthon Sai 3, Bang Phai, Bang Khae, Bangkok 10160",
    ages: "Children through adults",
    languages: ["Thai", "English"],
    delivery: ["At a centre"],
    services: [
      "Speech therapy",
      "Language development",
      "Occupational therapy",
      "Motor skills work",
      "Parent coaching",
      "Social-emotional group therapy",
    ],
    specialisms: [
      "Speech and language",
      "Developmental milestones",
      "Motor skills",
    ],
    phone: "+66 99 369 4744",
    email: "a.speechstation@gmail.com",
    description:
      "Speech Station combines speech and occupational therapy for speech, language, communication, motor skills and developmental milestones, with parent coaching and social-emotional group sessions alongside individual work. It sees children through to adults, in Thai and English.\n\nIts value to this directory is geographic. Almost every option here clusters along Sukhumvit, and families on the Thonburi and western side of the city routinely face an hour each way for a forty-five-minute session. Bang Khae is a realistic alternative if that is where you live.",
    checked: "September 2026",
  },
  {
    slug: "english-speech-therapy-bkk",
    name: "English Speech Therapy BKK",
    category: "Therapy clinic",
    area: "Bangkok",
    ages: "Children through adults",
    languages: ["English", "Thai"],
    delivery: ["At a centre", "In school", "At home"],
    services: [
      "Referral to English-speaking speech and language therapists",
      "Speech and language therapy",
    ],
    specialisms: ["Speech and language", "English-medium therapy"],
    phone: "+66 81 822 2008",
    email: "englishspeechtherapybkk@gmail.com",
    description:
      "This is a referral network rather than a clinic: a group of English-speaking speech and language therapists from various countries who live and work in Thailand, coordinated by speech pathologist Ann Gee Teo. You describe what you need and are matched to a therapist.\n\nIt solves a specific and common problem. Bangkok has capable speech therapists, but the pool who can deliver therapy in fluent English, and write reports an international school will act on, is much smaller, and it is not always obvious from the outside which is which.",
    checked: "September 2026",
  },
  {
    slug: "samitivej-special-needs-child-center",
    name: "Samitivej Special Needs Child Center",
    category: "Hospital clinic",
    area: "Watthana and Suan Luang",
    address:
      "Sukhumvit campus, Building 1, Floor 2; Srinakarin campus, Building B, 4th Floor",
    ages: "Infancy through adolescence",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Psychological assessment",
      "EEG and TOVA attention testing",
      "Speech therapy",
      "Occupational therapy",
      "Music, art and play therapy",
      "Developmental and behavioural therapy",
      "Social skills training",
      "Neurofeedback and biofeedback, Srinakarin only",
      "Child Development and Learning Center for early development",
    ],
    specialisms: [
      "Autism",
      "ADHD and attention",
      "Developmental disorders",
      "Learning disabilities",
      "Behaviour and emotions",
    ],
    website:
      "https://www.samitivejhospitals.com/center/detail/special-needs-child-center",
    phone: "+66 2022 2236",
    description:
      "Samitivej runs both a Special Needs Child Center and a Child Development and Learning Center, staffed by psychiatrists, psychologists, therapists and special education teachers, across its Sukhumvit and Srinakarin campuses. Between them they cover formal diagnosis, psychological assessment, EEG, TOVA attention testing, and then the therapy that follows: speech, occupational, music, art and play therapy plus social skills training. Srinakarin additionally offers neurofeedback and biofeedback.\n\nThe reason to start here rather than at a private centre is diagnosis. A hospital paediatric psychiatrist's report carries weight with schools, insurers and, later, exam boards, in a way that an informal opinion does not. Both campuses run 7:00 to 20:00 daily, and English is standard.",
    note: "Private hospital pricing. Check with your insurer first, as developmental assessment and therapy are excluded from many expat policies even where the hospital itself is covered.",
    checked: "September 2026",
  },
  {
    slug: "bangkok-hospital-child-development",
    name: "Bangkok Hospital Child Development Neuropsychiatric Clinic",
    category: "Hospital clinic",
    area: "Huai Khwang",
    address: "4th Floor, Bangkok Hospital Building, Bangkok",
    ages: "Children and adolescents",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Developmental and behavioural paediatric evaluation",
      "Counselling",
      "Treatment and medication management",
    ],
    specialisms: [
      "Dyslexia and learning disorders",
      "ADHD and oppositional behaviour",
      "Tics and Tourette syndrome",
      "Autism and cerebral palsy",
      "Speech, language and motor delay",
      "Sleep, feeding and toileting difficulties",
    ],
    website:
      "https://www.bangkokhospital.com/en/bangkok/center-clinic/child-wellness/the-chidevelopment-neuropsychiatric-clinic/overview",
    phone: "+66 2310 3006",
    description:
      "Bangkok Hospital's developmental-behavioural paediatricians evaluate, counsel and treat across a wide range: learning disorders including dyslexia and difficulties with writing and maths, ADHD and oppositional behaviour, tics and Tourette syndrome, autism spectrum disorders and cerebral palsy, speech, language and motor delays, and the everyday but exhausting problems of sleep, feeding and toilet training.\n\nIt is a good first stop when you are not yet sure what you are dealing with and need a medical opinion before committing to a therapy path. Clinic hours are daily, 8:00 to 16:00, and services are available in English.",
    note: "Private hospital pricing. Confirm what your insurance covers before the first appointment.",
    checked: "September 2026",
  },
  {
    slug: "manarom-hospital-child-adolescent",
    name: "Manarom Hospital, Child and Adolescent Services",
    category: "Hospital clinic",
    area: "Bang Na",
    address: "9 Sukhumvit 70/3, Bang Na Tai, Bang Na, Bangkok 10260",
    ages: "Infancy to 18",
    languages: ["English", "Thai"],
    delivery: ["At a centre"],
    services: [
      "Psychiatric and psychological assessment",
      "Treatment for ADHD, autism and developmental delay",
      "Mood, anxiety and behavioural disorder treatment",
      "Family counselling",
      "Medication consultation",
    ],
    specialisms: [
      "Child and adolescent psychiatry",
      "ADHD",
      "Autism",
      "Anxiety and mood",
      "Behavioural disorders",
    ],
    website: "https://www.manarom.com/child_eng.html",
    phone: "+66 2725 9595",
    description:
      "Manarom is a specialist psychiatric hospital, and its child and adolescent service covers infancy to 18 with child and adolescent psychiatrists, psychologists and social workers working as a team. It handles psychiatric and psychological assessment, ADHD, autism and developmental delay, mood and anxiety disorders, behavioural disorders, family counselling and medication.\n\nBecause psychiatry is what the hospital does rather than one department among many, it is the appropriate referral when a learning difficulty sits alongside something heavier: severe anxiety, school refusal, depression, or behaviour that has become unmanageable at home. Services are available in English.",
    checked: "September 2026",
  },
  {
    slug: "rajanukul-institute",
    name: "Rajanukul Institute",
    category: "Government service",
    area: "Din Daeng",
    address:
      "Rajanukul Institute, Din Daeng, Bangkok, with an early intervention centre at Khlong Kum",
    ages: "Birth to 18",
    languages: ["Thai"],
    delivery: ["At a centre"],
    services: [
      "Diagnosis and treatment for intellectual disability",
      "Learning disorder clinic",
      "Down syndrome clinic",
      "Genetic counselling",
      "Early intervention, ages 0 to 6",
      "Parent management training",
      "Department of Special Education",
      "Department of Medical Rehabilitation",
    ],
    specialisms: [
      "Intellectual disability",
      "Learning disorders",
      "Down syndrome",
      "Behavioural and emotional difficulties",
    ],
    website: "https://eng.rajanukul.go.th",
    phone: "+66 2 248 8900",
    description:
      "Rajanukul is Thailand's national institute for children with intellectual disabilities, operating under the Department of Mental Health. It runs outpatient clinics for children from birth to 18 with intellectual disability, learning disorders and emotional or behavioural difficulties, plus specialist clinics for Down syndrome, genetic counselling and learning disorders, an early intervention service for children aged 0 to 6, parent management training, and its own departments of special education and medical rehabilitation.\n\nIt belongs in this directory for a reason nobody else here can match: cost. Private assessment and therapy in Bangkok runs to tens of thousands of baht, and a great many families, Thai and foreign, simply cannot pay it. Rajanukul is the public route, and it is a serious institution with a research and training function, not a last resort.",
    note: "Services are delivered in Thai and waiting times can be long. Bring a Thai-speaking friend or interpreter. Foreign nationals should call ahead to confirm eligibility and what documents to bring.",
    checked: "September 2026",
  },
];

export const ALL_CATEGORIES: ProviderCategory[] = Array.from(
  new Set(PROVIDERS.map((p) => p.category)),
).sort() as ProviderCategory[];

export const ALL_AREAS: string[] = Array.from(
  new Set(PROVIDERS.map((p) => p.area)),
).sort();

export const ALL_SPECIALISMS: string[] = Array.from(
  new Set(PROVIDERS.flatMap((p) => p.specialisms ?? [])),
).sort();
