export type Budget = "under400k" | "over400k" | "unknown";

export interface School {
  name: string;
  slug: string;
  curricula: string[];
  budget: Budget;
}

// Curriculum + budget tags. Budget is average annual tuition across grades,
// split at 400,000 THB/year, based on 2026/2027 published fee ranges where
// available. Schools that don't publish fees are conservatively tagged
// "under400k" pending direct confirmation.
export const SCHOOLS: School[] = [
  { name: "ABC Pathways International Kindergarten", slug: "abc-pathways-international-kindergarten", curricula: ["British"], budget: "under400k" },
  { name: "Anglo Singapore International School", slug: "anglo-singapore-international-school", curricula: ["British", "Singaporean"], budget: "unknown" },
  { name: "Annabel's Early Years International School", slug: "annabels-early-years-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Ascot International School", slug: "ascot-international-school", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Associe International Kindergarten Bangkok", slug: "associe-international-kindergarten-bangkok", curricula: ["American", "Japanese", "Thai"], budget: "under400k" },
  { name: "Bangkok Christian International School", slug: "bangkok-christian-international-school", curricula: ["American", "Christian"], budget: "under400k" },
  { name: "Bangkok Grace International School (BGIS)", slug: "bangkok-grace-international-school-bgis", curricula: ["American", "Christian"], budget: "under400k" },
  { name: "Bangkok Patana School", slug: "bangkok-patana-school", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Bangkok Prep", slug: "bangkok-prep", curricula: ["British"], budget: "over400k" },
  { name: "Basis International School Bangkok", slug: "basis-international-school-bangkok", curricula: ["American"], budget: "over400k" },
  { name: "Berkeley International School Bangkok", slug: "berkeley-international-school-bangkok", curricula: ["American"], budget: "over400k" },
  { name: "BERNIE British International Prep & Early Years", slug: "bernie-british-international-prep-kindergarten-early-years", curricula: ["British"], budget: "under400k" },
  { name: "Bright Skies International School", slug: "bright-skies-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Brighton College Bangkok", slug: "brighton-college-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "British Columbia International School", slug: "british-columbia-international-school", curricula: ["Canadian"], budget: "unknown" },
  { name: "Bromsgrove International School Thailand", slug: "bromsgrove-international-school-thailand", curricula: ["British"], budget: "over400k" },
  { name: "Canadian International School of Thailand", slug: "canadian-international-school-of-thailand", curricula: ["Canadian", "International Baccalaureate"], budget: "under400k" },
  { name: "Centurion International School Bangkok", slug: "centurion-international-school-bangkok", curricula: ["British"], budget: "under400k" },
  { name: "Charter International School", slug: "charter-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Concordian International School Bangkok", slug: "concordian-bangkok-concordian-international-school-bangkok", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "Denla British School", slug: "denla-british-school", curricula: ["British"], budget: "over400k" },
  { name: "DPREP Bangkok", slug: "dprep-bangkok", curricula: ["International Baccalaureate", "American"], budget: "over400k" },
  { name: "Ekamai International School", slug: "ekamai-international-school", curricula: ["American", "Adventist"], budget: "under400k" },
  { name: "Garden International School Bangkok", slug: "garden-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "Global English School", slug: "global-english-school", curricula: ["Blended Learning"], budget: "under400k" },
  { name: "Global Indian International School", slug: "global-indian-international-school", curricula: ["Indian"], budget: "under400k" },
  { name: "Glory Singapore International School", slug: "glory-singapore-international-school", curricula: ["British", "Singaporean"], budget: "under400k" },
  { name: "Hampton International School", slug: "hampton-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Harrow International School Bangkok", slug: "harrow-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "Heathfield International School", slug: "heathfield-international-school", curricula: ["British"], budget: "over400k" },
  { name: "International Community School", slug: "international-community-school", curricula: ["American", "Christian"], budget: "over400k" },
  { name: "International Montessori Center", slug: "international-montessori-center", curricula: ["British", "Montessori"], budget: "under400k" },
  { name: "International Pioneers School", slug: "international-pioneers-school", curricula: ["British"], budget: "under400k" },
  { name: "IPC International Kindergarten", slug: "ipc-international-kindergarten", curricula: ["British"], budget: "under400k" },
  { name: "Kevalee International School", slug: "kevalee-international-school", curricula: ["American"], budget: "under400k" },
  { name: "KiddyKare International Kindergarten", slug: "kiddykare-international-kindergarten", curricula: ["British"], budget: "under400k" },
  { name: "KIS International School Bangkok", slug: "kis-international-school-bangkok", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "KPIS International School", slug: "kpis-international-school", curricula: ["American"], budget: "unknown" },
  { name: "MYIS International School", slug: "magic-years-international-school-thailand", curricula: ["International Baccalaureate", "American"], budget: "over400k" },
  { name: "NIST International School Bangkok", slug: "nist-international-school-bangkok", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "The American School of Bangkok (ASB)", slug: "the-american-school-of-bangkok-asb", curricula: ["American", "International Baccalaureate"], budget: "over400k" },
  { name: "The British School of Bangkok (Topsy Turvy)", slug: "the-british-school-of-bangkok-topsy-turvy-international-school", curricula: ["British"], budget: "under400k" },
  { name: "The Country School by ELC", slug: "the-country-school-by-elc", curricula: ["British"], budget: "under400k" },
  { name: "The First Steps International School", slug: "the-first-steps-international-school", curricula: ["British"], budget: "under400k" },
  { name: "The Purple Elephant 55", slug: "the-purple-elephant-55", curricula: ["English Program"], budget: "under400k" },
  { name: "The Tiny Seeds International Pre-School", slug: "the-tiny-seeds-international-pre-school-bangkok", curricula: ["English Program"], budget: "under400k" },
  { name: "The Village International Education Centre (VIE)", slug: "the-village-international-education-centre-vie", curricula: ["British"], budget: "over400k" },
  { name: "Thonglor Greenfield Nursery", slug: "thonglor-greenfield-nursery", curricula: ["British"], budget: "under400k" },
  { name: "Tiny Tots International School", slug: "tiny-tots-international-school", curricula: ["British", "Indian"], budget: "under400k" },
  { name: "Traill International School", slug: "traill-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Trinity International School", slug: "trinity-international-school", curricula: ["American", "Adventist"], budget: "under400k" },
  { name: "Verso International School", slug: "verso-international-school", curricula: ["American"], budget: "over400k" },
  { name: "Wellington International School Bangkok", slug: "wellington-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "Shrewsbury International School Bangkok", slug: "shrewsbury-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "International School Bangkok (ISB)", slug: "international-school-bangkok-isb", curricula: ["American", "International Baccalaureate"], budget: "over400k" },
  { name: "Ruamrudee International School (RIS)", slug: "ruamrudee-international-school-ris", curricula: ["American", "International Baccalaureate"], budget: "over400k" },
  { name: "King's College International School Bangkok", slug: "kings-college-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "UWC Thailand", slug: "uwc-thailand", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "St Andrews International School Bangkok", slug: "st-andrews-international-school-bangkok", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Wells International School", slug: "wells-international-school", curricula: ["American", "International Baccalaureate"], budget: "over400k" },
  { name: "Regent's International School Bangkok", slug: "regents-international-school-bangkok", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Amnuay Silpa School", slug: "amnuay-silpa-school", curricula: ["British", "Thai"], budget: "over400k" },
  { name: "Invictus International Programme", slug: "invictus-international-programme", curricula: ["British"], budget: "over400k" },
  { name: "RBIS International School", slug: "rbis-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Singapore International School of Bangkok", slug: "singapore-international-school-of-bangkok", curricula: ["British", "International Baccalaureate", "Singaporean"], budget: "over400k" },
  { name: "Norwich International School", slug: "norwich-international-school", curricula: ["International Baccalaureate", "British"], budget: "over400k" },
  { name: "Sequoia Nova International Primary School", slug: "sequoia-nova-international-primary-school", curricula: ["French"], budget: "under400k" },
  { name: "Rose Marie Academy", slug: "rose-marie-academy", curricula: ["American"], budget: "over400k" },
  { name: "XCL American School of Bangkok", slug: "xcl-american-school-of-bangkok", curricula: ["American"], budget: "over400k" },
  { name: "Thai-Singapore International School", slug: "thai-singapore-international-school", curricula: ["British", "Singaporean"], budget: "unknown" },
  { name: "Bangkok Adventist International School", slug: "bangkok-adventist-international-school", curricula: ["American", "Adventist"], budget: "unknown" },
  { name: "Rising Oaks International School Bangkok", slug: "rising-oaks-international-school-bangkok", curricula: ["British"], budget: "under400k" },
  { name: "Astra Academy International School", slug: "astra-academy-international-school", curricula: ["British"], budget: "over400k" },
  { name: "WeLearn Academy", slug: "welearn-academy", curricula: ["American", "British", "Thai"], budget: "under400k" },
  { name: "St. Mark's International School", slug: "st-marks-international-school", curricula: ["Australian", "Singaporean"], budget: "unknown" },
  { name: "Australian International School Bangkok", slug: "australian-international-school-bangkok", curricula: ["British", "Australian"], budget: "over400k" },
  { name: "International Christian School Nonthaburi", slug: "international-christian-school-nonthaburi", curricula: ["American", "Christian"], budget: "over400k" },
  { name: "Beaconhouse Yamsaard International School", slug: "beaconhouse-yamsaard-international-school", curricula: ["British"], budget: "under400k" },
  { name: "BSB British International Primary School", slug: "bsb-british-international-primary-school", curricula: ["British"], budget: "over400k" },
  { name: "Crescent International School", slug: "crescent-international-school", curricula: ["British"], budget: "unknown" },
  { name: "Royce Royal International School", slug: "royce-royal-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Dulwich College International School Bangkok", slug: "dulwich-college-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "Thai-Chinese International School", slug: "thai-chinese-international-school", curricula: ["American"], budget: "over400k" },
  { name: "Kids Academy International School", slug: "kids-academy-international-school", curricula: ["British", "Chinese", "Japanese"], budget: "unknown" },
  { name: "Ramkhamhaeng Advent International School", slug: "ramkhamhaeng-advent-international-school", curricula: ["Adventist", "American"], budget: "under400k" },
  { name: "Pan-Asia International School", slug: "pan-asia-international-school", curricula: ["International Baccalaureate", "American"], budget: "unknown" },
  { name: "NIVA American International School", slug: "niva-american-international-school", curricula: ["American", "Christian"], budget: "over400k" },
  { name: "John Wyatt Montessori Bangkok", slug: "john-wyatt-montessori-bangkok", curricula: ["American", "Montessori"], budget: "unknown" },
  { name: "SPGS International School Bangkok", slug: "spgs-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "New Day Learning", slug: "new-day-learning", curricula: ["Special Educational Needs"], budget: "unknown" },
  { name: "British Mandarin International School", slug: "british-mandarin-international-school", curricula: ["British", "Chinese"], budget: "over400k" },
  { name: "Lertlah School", slug: "lertlah-school", curricula: ["Canadian"], budget: "unknown" },
  { name: "St. Andrews International School Sathorn", slug: "st-andrews-international-school-sathorn", curricula: ["British"], budget: "over400k" },
  { name: "Westminster College Bangkok", slug: "westminster-college-bangkok", curricula: ["American", "British"], budget: "unknown" },
  { name: "Modern International School Bangkok", slug: "modern-international-school-bangkok", curricula: ["British"], budget: "under400k" },
  { name: "Thai International School", slug: "thai-international-school", curricula: ["American"], budget: "over400k" },
  { name: "Satit Pattana Secondary School", slug: "satit-pattana-secondary-school", curricula: ["British"], budget: "unknown" },
  { name: "Kincaid International School of Bangkok", slug: "kincaid-international-school-of-bangkok", curricula: ["International Baccalaureate"], budget: "under400k" },
  { name: "Siam International School", slug: "siam-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Wycombe Abbey International School Bangkok", slug: "wycombe-abbey-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "St. Andrews International School Dusit", slug: "st-andrews-international-school-dusit", curricula: ["British"], budget: "over400k" },
  { name: "Siam Singapore International School", slug: "siam-singapore-international-school", curricula: ["British", "Singaporean"], budget: "unknown" },
  { name: "Aster International School Bangkok", slug: "aster-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "RIS Swiss Section Deutschsprachige Schule Bangkok", slug: "ris-swiss-section-deutschsprachige-schule-bangkok", curricula: ["Swiss", "International", "German"], budget: "over400k" },
  { name: "Lycée Français International de Bangkok", slug: "lycee-francais-international-de-bangkok", curricula: ["French"], budget: "over400k" },
  { name: "TSI International School", slug: "tsi-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Future Steps International School Bangkok", slug: "future-steps-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "King Mongkut's International Demonstration School", slug: "king-mongkuts-international-demonstration-school", curricula: ["American"], budget: "over400k" },
  { name: "The Jataka School", slug: "the-jataka-school", curricula: ["British", "Buddhist"], budget: "under400k" },
  { name: "Sarasas Ektra School", slug: "sarasas-ektra-school", curricula: ["Catholic", "International", "Thai"], budget: "unknown" },
  { name: "AIT International School", slug: "ait-international-school", curricula: ["American"], budget: "under400k" },
  { name: "St. Andrews Samakee International School", slug: "st-andrews-samakee-international-school", curricula: ["British"], budget: "over400k" },
  { name: "St. Andrews International School Sukhumvit 107", slug: "st-andrews-international-school-sukhumvit-107", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Knightsbridge House International School Nonthaburi", slug: "knightsbridge-house-international-school-nonthaburi", curricula: ["British"], budget: "under400k" },
  { name: "Raffles American School Bangkok", slug: "raffles-american-school-bangkok", curricula: ["American"], budget: "under400k" },
  { name: "RC International School", slug: "rc-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Roong Aroon International School", slug: "roong-aroon-international-school", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "Satit Bilingual School of Rangsit University", slug: "satit-bilingual-school-of-rangsit-university", curricula: ["British", "International Baccalaureate"], budget: "under400k" },
  { name: "Montessori Academy Bangkok International School", slug: "montessori-academy-bangkok-international-school", curricula: ["American", "Montessori"], budget: "over400k" },
  { name: "Pensmith School", slug: "pensmith-school", curricula: ["British"], budget: "unknown" },
  { name: "Bangkok-Chicago Christian International School", slug: "bangkok-chicago-christian-international-school", curricula: ["American", "Christian"], budget: "unknown" },
];

export const ALL_CURRICULA = Array.from(
  new Set(SCHOOLS.flatMap((s) => s.curricula))
).sort();
