export type Budget = "under400k" | "over400k" | "unknown";

export interface School {
  name: string;
  slug: string;
  curricula: string[];
  budget: Budget;
  website?: string;
  description?: string;
  founded?: number;
  ageRange?: string;
  languageOfInstruction?: string;
  feeRange?: string;
}

// Curriculum + budget tags. Budget is average annual tuition across grades,
// split at 400,000 THB/year, based on 2026/2027 published fee ranges where
// available. Schools that don't publish fees are conservatively tagged
// "under400k" pending direct confirmation.
export const SCHOOLS: School[] = [
  { name: "ABC Pathways International Kindergarten", slug: "abc-pathways-international-kindergarten", curricula: ["British"], budget: "under400k" },
  { name: "Anglo Singapore International School", slug: "anglo-singapore-international-school", curricula: ["British", "Singaporean"], budget: "unknown" },
  { name: "Annabel's Early Years International School", slug: "annabels-early-years-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Ascot International School", slug: "ascot-international-school", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Associe International Kindergarten Bangkok", slug: "associe-international-kindergarten-bangkok", curricula: ["American", "Japanese", "Thai"], budget: "under400k" },
  { name: "Bangkok Christian International School", slug: "bangkok-christian-international-school", curricula: ["American", "Christian"], budget: "under400k" },
  { name: "Bangkok Grace International School (BGIS)", slug: "bangkok-grace-international-school-bgis", curricula: ["American", "Christian"], budget: "under400k" },
  { name: "Bangkok Patana School", slug: "bangkok-patana-school", curricula: ["British", "International Baccalaureate"], budget: "over400k", website: "https://www.patana.ac.th", founded: 1957, description: "Thailand's oldest and largest British international school, founded by a group of parents on a Bangna campus that now spans roughly 40 acres. Patana teaches the English National Curriculum through to IGCSE and A-Levels and is run as a not-for-profit under parent governance.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "545,000 to 1,044,000 THB/year" },
  { name: "Bangkok Prep", slug: "bangkok-prep", curricula: ["British"], budget: "over400k", website: "https://www.bangkokprep.ac.th", founded: 2003, description: "Founded by two educators with backgrounds in international kindergarten education, Bangkok Prep follows the National Curriculum for England on a Sukhumvit 77 campus, offering IGCSE, A-Levels, and BTEC pathways for Sixth Form students.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "384,800 to 862,200 THB/year" },
  { name: "Basis International School Bangkok", slug: "basis-international-school-bangkok", curricula: ["American"], budget: "over400k" },
  { name: "Berkeley International School Bangkok", slug: "berkeley-international-school-bangkok", curricula: ["American"], budget: "over400k" },
  { name: "BERNIE British International Prep & Early Years", slug: "bernie-british-international-prep-kindergarten-early-years", curricula: ["British"], budget: "under400k" },
  { name: "Bright Skies International School", slug: "bright-skies-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Brighton College Bangkok", slug: "brighton-college-bangkok", curricula: ["British"], budget: "over400k", website: "https://brightoncollege.ac.th", description: "A sister school to Brighton College in the UK — named England's School of the Decade by The Sunday Times — offering a British curriculum with a strong focus on pastoral care and individual student development.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "590,300 to 1,021,800 THB/year" },
  { name: "British Columbia International School", slug: "british-columbia-international-school", curricula: ["Canadian"], budget: "unknown" },
  { name: "Bromsgrove International School Thailand", slug: "bromsgrove-international-school-thailand", curricula: ["British"], budget: "over400k", website: "https://www.bromsgrove.ac.th", founded: 2002, description: "A British curriculum day and boarding school affiliated with Bromsgrove School in England (founded 1553), located within a golf course estate near Suvarnabhumi Airport. It offers IGCSE and A-Levels across two campuses in Min Buri.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "259,100 to 680,100 THB/year" },
  { name: "Canadian International School of Thailand", slug: "canadian-international-school-of-thailand", curricula: ["Canadian", "International Baccalaureate"], budget: "under400k" },
  { name: "Centurion International School Bangkok", slug: "centurion-international-school-bangkok", curricula: ["British"], budget: "under400k" },
  { name: "Charter International School", slug: "charter-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Concordian International School Bangkok", slug: "concordian-bangkok-concordian-international-school-bangkok", curricula: ["International Baccalaureate"], budget: "over400k", website: "https://www.concordian.ac.th", description: "An IB World School near Bangna–Trad that teaches through English, Mandarin Chinese, and Thai, with instruction split roughly evenly between English and Chinese. Concordian offers the IB continuum from early years through Diploma.", ageRange: "Ages 2 to 18", languageOfInstruction: "English, Chinese, Thai", feeRange: "646,200 to 993,300 THB/year" },
  { name: "Denla British School", slug: "denla-british-school", curricula: ["British"], budget: "over400k" },
  { name: "DPREP Bangkok", slug: "dprep-bangkok", curricula: ["International Baccalaureate", "American"], budget: "over400k" },
  { name: "Ekamai International School", slug: "ekamai-international-school", curricula: ["American", "Adventist"], budget: "under400k" },
  { name: "Garden International School Bangkok", slug: "garden-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "Global English School", slug: "global-english-school", curricula: ["Blended Learning"], budget: "under400k" },
  { name: "Global Indian International School", slug: "global-indian-international-school", curricula: ["Indian"], budget: "under400k" },
  { name: "Glory Singapore International School", slug: "glory-singapore-international-school", curricula: ["British", "Singaporean"], budget: "under400k" },
  { name: "Hampton International School", slug: "hampton-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Harrow International School Bangkok", slug: "harrow-international-school-bangkok", curricula: ["British"], budget: "over400k", website: "https://www.harrowschool.ac.th", founded: 1998, description: "A boarding and day school in Don Mueang affiliated with Harrow School in London, spread across a roughly 35-acre suburban campus. It follows the British curriculum through IGCSE and A-Levels with a strong emphasis on its house system and pastoral care.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "634,600 to 1,063,000 THB/year" },
  { name: "Heathfield International School", slug: "heathfield-international-school", curricula: ["British"], budget: "over400k" },
  { name: "International Community School", slug: "international-community-school", curricula: ["American", "Christian"], budget: "over400k" },
  { name: "International Montessori Center", slug: "international-montessori-center", curricula: ["British", "Montessori"], budget: "under400k" },
  { name: "International Pioneers School", slug: "international-pioneers-school", curricula: ["British"], budget: "under400k" },
  { name: "IPC International Kindergarten", slug: "ipc-international-kindergarten", curricula: ["British"], budget: "under400k" },
  { name: "Kevalee International School", slug: "kevalee-international-school", curricula: ["American"], budget: "under400k" },
  { name: "KiddyKare International Kindergarten", slug: "kiddykare-international-kindergarten", curricula: ["British"], budget: "under400k" },
  { name: "KIS International School Bangkok", slug: "kis-international-school-bangkok", curricula: ["International Baccalaureate"], budget: "over400k", website: "https://www.kis.ac.th", description: "A mid-sized IB continuum school offering the full PYP, MYP, and DP programmes on a campus of more than 25,000 square meters. KIS is known for strong, above-average IB exam results within an intentionally smaller community.", ageRange: "Ages 3 to 19", languageOfInstruction: "English", feeRange: "459,800 to 984,700 THB/year" },
  { name: "KPIS International School", slug: "kpis-international-school", curricula: ["American"], budget: "unknown" },
  { name: "MYIS International School", slug: "magic-years-international-school-thailand", curricula: ["International Baccalaureate", "American"], budget: "over400k" },
  { name: "NIST International School Bangkok", slug: "nist-international-school-bangkok", curricula: ["International Baccalaureate"], budget: "over400k", website: "https://www.nist.ac.th", founded: 1992, description: "Founded with support from the Bangkok-based UN community, NIST was Thailand's first full International Baccalaureate World School, offering the complete PYP-MYP-DP continuum. It's a not-for-profit, parent-governed school in central Sukhumvit.", ageRange: "Ages 3 to 18", languageOfInstruction: "English", feeRange: "650,200 to 1,132,800 THB/year" },
  { name: "The American School of Bangkok (ASB)", slug: "the-american-school-of-bangkok-asb", curricula: ["American", "International Baccalaureate"], budget: "over400k" },
  { name: "The British School of Bangkok (Topsy Turvy)", slug: "the-british-school-of-bangkok-topsy-turvy-international-school", curricula: ["British"], budget: "under400k" },
  { name: "The Country School by ELC", slug: "the-country-school-by-elc", curricula: ["British"], budget: "under400k" },
  { name: "The First Steps International School", slug: "the-first-steps-international-school", curricula: ["British"], budget: "under400k" },
  { name: "The Purple Elephant 55", slug: "the-purple-elephant-55", curricula: ["English Program"], budget: "under400k" },
  { name: "The Tiny Seeds International Pre-School", slug: "the-tiny-seeds-international-pre-school-bangkok", curricula: ["English Program"], budget: "under400k" },
  { name: "The Village International Education Centre (VIE)", slug: "the-village-international-education-centre-vie", curricula: ["British"], budget: "over400k" },
  { name: "Thonglor Greenfield Nursery", slug: "thonglor-greenfield-nursery", curricula: ["British"], budget: "under400k" },
  { name: "Tiny Tots International School", slug: "tiny-tots-international-school", curricula: ["British", "Indian"], budget: "under400k" },
  { name: "Traill International School", slug: "traill-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Trinity International School", slug: "trinity-international-school", curricula: ["American", "Adventist"], budget: "under400k" },
  { name: "Verso International School", slug: "verso-international-school", curricula: ["American"], budget: "over400k" },
  { name: "Wellington International School Bangkok", slug: "wellington-international-school-bangkok", curricula: ["British"], budget: "over400k", website: "https://www.wellingtoncollege.ac.th", founded: 2018, description: "The first Wellington College campus in ASEAN, affiliated with the 160-year-old Wellington College in Berkshire, England. Set on a roughly 70-rai campus, it teaches a British curriculum through IGCSE and A-Levels and holds COBIS Patron's Accreditation.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "615,250 to 1,240,137 THB/year" },
  { name: "Shrewsbury International School Bangkok", slug: "shrewsbury-international-school-bangkok", curricula: ["British"], budget: "over400k", website: "https://www.shrewsbury.ac.th", founded: 2003, description: "The Bangkok sibling of England's 500-year-old Shrewsbury School, teaching the National Curriculum for England through IGCSE and A-Level. It operates two campuses — a riverside site along the Chao Phraya and a second City Campus in Huai Khwang.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "691,800 to 1,208,400 THB/year" },
  { name: "International School Bangkok (ISB)", slug: "international-school-bangkok-isb", curricula: ["American", "International Baccalaureate"], budget: "over400k", website: "https://www.isb.ac.th", founded: 1951, description: "One of Thailand's oldest international schools, ISB sits on a large campus in Nichada Thani, Nonthaburi. It blends an American curriculum with the IB Diploma Programme, giving graduating students a choice between AP and IB pathways.", ageRange: "Ages 3 to 18", languageOfInstruction: "English", feeRange: "681,000 to 1,219,000 THB/year" },
  { name: "Ruamrudee International School (RIS)", slug: "ruamrudee-international-school-ris", curricula: ["American", "International Baccalaureate"], budget: "over400k", website: "https://www.rism.ac.th", founded: 1957, description: "One of Thailand's oldest international schools and the first in the country to achieve WASC accreditation. RIS is a private, non-profit, interfaith day school combining American and IB pathways with a strong emphasis on values and character education.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "548,400 to 1,527,000 THB/year" },
  { name: "King's College International School Bangkok", slug: "kings-college-international-school-bangkok", curricula: ["British"], budget: "over400k", website: "https://www.kingsbangkok.ac.th", founded: 2020, description: "The first South-East Asian campus of King's College School, Wimbledon, located in the Ratchada–Rama 3 area. It offers a British curriculum through IGCSE and A-Levels, working closely with its London sister school on curriculum and pastoral care.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "616,000 to 1,063,000 THB/year" },
  { name: "UWC Thailand", slug: "uwc-thailand", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "St Andrews International School Bangkok", slug: "st-andrews-international-school-bangkok", curricula: ["British", "International Baccalaureate"], budget: "over400k", website: "https://www.nordangliaeducation.com/sta-bangkok", founded: 1997, description: "Part of the Nord Anglia Education network of premium international schools, St Andrews Bangkok runs primary and high school campuses in the Sukhumvit area, teaching the British curriculum through IGCSE and the IB Diploma Programme.", ageRange: "Ages 2 to 18", languageOfInstruction: "English", feeRange: "400,700 to 873,800 THB/year" },
  { name: "Wells International School", slug: "wells-international-school", curricula: ["American", "International Baccalaureate"], budget: "over400k" },
  { name: "Regent's International School Bangkok", slug: "regents-international-school-bangkok", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Amnuay Silpa School", slug: "amnuay-silpa-school", curricula: ["British", "Thai"], budget: "over400k" },
  { name: "Invictus International Programme", slug: "invictus-international-programme", curricula: ["British"], budget: "over400k" },
  { name: "RBIS International School", slug: "rbis-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Singapore International School of Bangkok", slug: "singapore-international-school-of-bangkok", curricula: ["British", "International Baccalaureate", "Singaporean"], budget: "over400k" },
  { name: "Norwich International School", slug: "norwich-international-school", curricula: ["International Baccalaureate", "British"], budget: "over400k" },
  { name: "Sequoia Nova International Primary School", slug: "sequoia-nova-international-primary-school", curricula: ["French"], budget: "under400k" },
  { name: "Rose Marie Academy", slug: "rose-marie-academy", curricula: ["American"], budget: "over400k" },
  { name: "XCL American School of Bangkok", slug: "xcl-american-school-of-bangkok", curricula: ["American"], budget: "over400k" },
  { name: "Thai-Singapore International School", slug: "thai-singapore-international-school", curricula: ["British", "Singaporean"], budget: "unknown" },
  { name: "Bangkok Adventist International School", slug: "bangkok-adventist-international-school", curricula: ["American", "Adventist"], budget: "unknown" },
  { name: "Rising Oaks International School Bangkok", slug: "rising-oaks-international-school-bangkok", curricula: ["British"], budget: "under400k" },
  { name: "Astra Academy International School", slug: "astra-academy-international-school", curricula: ["British"], budget: "over400k" },
  { name: "WeLearn Academy", slug: "welearn-academy", curricula: ["American", "British", "Thai"], budget: "under400k" },
  { name: "St. Mark's International School", slug: "st-marks-international-school", curricula: ["Australian", "Singaporean"], budget: "unknown" },
  { name: "Australian International School Bangkok", slug: "australian-international-school-bangkok", curricula: ["British", "Australian"], budget: "over400k" },
  { name: "International Christian School Nonthaburi", slug: "international-christian-school-nonthaburi", curricula: ["American", "Christian"], budget: "over400k" },
  { name: "Beaconhouse Yamsaard International School", slug: "beaconhouse-yamsaard-international-school", curricula: ["British"], budget: "under400k" },
  { name: "BSB British International Primary School", slug: "bsb-british-international-primary-school", curricula: ["British"], budget: "over400k" },
  { name: "Crescent International School", slug: "crescent-international-school", curricula: ["British"], budget: "unknown" },
  { name: "Royce Royal International School", slug: "royce-royal-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Dulwich College International School Bangkok", slug: "dulwich-college-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "Thai-Chinese International School", slug: "thai-chinese-international-school", curricula: ["American"], budget: "over400k" },
  { name: "Kids Academy International School", slug: "kids-academy-international-school", curricula: ["British", "Chinese", "Japanese"], budget: "unknown" },
  { name: "Ramkhamhaeng Advent International School", slug: "ramkhamhaeng-advent-international-school", curricula: ["Adventist", "American"], budget: "under400k" },
  { name: "Pan-Asia International School", slug: "pan-asia-international-school", curricula: ["International Baccalaureate", "American"], budget: "unknown" },
  { name: "NIVA American International School", slug: "niva-american-international-school", curricula: ["American", "Christian"], budget: "over400k" },
  { name: "John Wyatt Montessori Bangkok", slug: "john-wyatt-montessori-bangkok", curricula: ["American", "Montessori"], budget: "unknown" },
  { name: "SPGS International School Bangkok", slug: "spgs-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "New Day Learning", slug: "new-day-learning", curricula: ["Special Educational Needs"], budget: "unknown" },
  { name: "British Mandarin International School", slug: "british-mandarin-international-school", curricula: ["British", "Chinese"], budget: "over400k" },
  { name: "Lertlah School", slug: "lertlah-school", curricula: ["Canadian"], budget: "unknown" },
  { name: "St. Andrews International School Sathorn", slug: "st-andrews-international-school-sathorn", curricula: ["British"], budget: "over400k" },
  { name: "Westminster College Bangkok", slug: "westminster-college-bangkok", curricula: ["American", "British"], budget: "unknown" },
  { name: "Modern International School Bangkok", slug: "modern-international-school-bangkok", curricula: ["British"], budget: "under400k" },
  { name: "Thai International School", slug: "thai-international-school", curricula: ["American"], budget: "over400k" },
  { name: "Satit Pattana Secondary School", slug: "satit-pattana-secondary-school", curricula: ["British"], budget: "unknown" },
  { name: "Kincaid International School of Bangkok", slug: "kincaid-international-school-of-bangkok", curricula: ["International Baccalaureate"], budget: "under400k" },
  { name: "Siam International School", slug: "siam-international-school", curricula: ["British"], budget: "over400k" },
  { name: "Wycombe Abbey International School Bangkok", slug: "wycombe-abbey-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "St. Andrews International School Dusit", slug: "st-andrews-international-school-dusit", curricula: ["British"], budget: "over400k" },
  { name: "Siam Singapore International School", slug: "siam-singapore-international-school", curricula: ["British", "Singaporean"], budget: "unknown" },
  { name: "Aster International School Bangkok", slug: "aster-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "RIS Swiss Section Deutschsprachige Schule Bangkok", slug: "ris-swiss-section-deutschsprachige-schule-bangkok", curricula: ["Swiss", "International", "German"], budget: "over400k" },
  { name: "Lycée Français International de Bangkok", slug: "lycee-francais-international-de-bangkok", curricula: ["French"], budget: "over400k" },
  { name: "TSI International School", slug: "tsi-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Future Steps International School Bangkok", slug: "future-steps-international-school-bangkok", curricula: ["British"], budget: "over400k" },
  { name: "King Mongkut's International Demonstration School", slug: "king-mongkuts-international-demonstration-school", curricula: ["American"], budget: "over400k" },
  { name: "The Jataka School", slug: "the-jataka-school", curricula: ["British", "Buddhist"], budget: "under400k" },
  { name: "Sarasas Ektra School", slug: "sarasas-ektra-school", curricula: ["Catholic", "International", "Thai"], budget: "unknown" },
  { name: "AIT International School", slug: "ait-international-school", curricula: ["American"], budget: "under400k" },
  { name: "St. Andrews Samakee International School", slug: "st-andrews-samakee-international-school", curricula: ["British"], budget: "over400k" },
  { name: "St. Andrews International School Sukhumvit 107", slug: "st-andrews-international-school-sukhumvit-107", curricula: ["British", "International Baccalaureate"], budget: "over400k" },
  { name: "Knightsbridge House International School Nonthaburi", slug: "knightsbridge-house-international-school-nonthaburi", curricula: ["British"], budget: "under400k" },
  { name: "Raffles American School Bangkok", slug: "raffles-american-school-bangkok", curricula: ["American"], budget: "under400k" },
  { name: "RC International School", slug: "rc-international-school", curricula: ["British"], budget: "under400k" },
  { name: "Roong Aroon International School", slug: "roong-aroon-international-school", curricula: ["International Baccalaureate"], budget: "over400k" },
  { name: "Satit Bilingual School of Rangsit University", slug: "satit-bilingual-school-of-rangsit-university", curricula: ["British", "International Baccalaureate"], budget: "under400k" },
  { name: "Montessori Academy Bangkok International School", slug: "montessori-academy-bangkok-international-school", curricula: ["American", "Montessori"], budget: "over400k" },
  { name: "Pensmith School", slug: "pensmith-school", curricula: ["British"], budget: "unknown" },
  { name: "Bangkok-Chicago Christian International School", slug: "bangkok-chicago-christian-international-school", curricula: ["American", "Christian"], budget: "unknown" },
];

export const ALL_CURRICULA = Array.from(
  new Set(SCHOOLS.flatMap((s) => s.curricula))
).sort();
